### ISSUE TITLE
Provide TTF

### ISSUE THREAD

**Issue by musm** [alerque/libertinus#326]
Word has issues when exported documents with OTF typefaces in PDF format (they don't get embedded). Would it be possible to also ship TTF in addition to the OTF files?

**Comment by alerque** [comment]
Why should the burden for problems like this fall to an open source project like this to work around what is clearly a bug in expensive commercial software? Did you report this to Microsoft?

**Comment by khaledhosny** [comment]
Too much effort to do and maintain (and needing to handle the difference in rendering between TTF and OTF, differences in hinting strategies, and so on). So much effort to work around a limitation in MS Office. Not to mention user confusion on which version to use and download.

There are several alternative “PDF printers” for Windows that you can use to work around this.

**Comment by alerque** [comment]
I'm going to re-open this for review. Frankly I could care less if Word support. Given the level of control they maintain over the file format spec in the first place the fact that Microsoft of all people doesn't fix long standing bugs in their OpenType implementations in their flagship products just rubs me the wrong way. However there are a couple more reasons the extra work required to ship TTF versions *may* be worth it.

1. One is that if (and this is a big if, but it's a consideration) Libertinus is going to get listed on Google Fonts (see https://github.com/google/fonts/issues/12) then it would need to have a working TTF build pipeline because that's the format their, QA, build, and delivery pipeline requires.

2. There are *some* platforms and rasterization situations for which the hinting options available for TTF files *may be* preferable to those available for OTF.

At the end of the day it seems like OTF should still be our primary deliverable and somehow this would need to be documented to reduce confusion; but it *might* be worth the effort to review the hinting settings and add TTF as an alternative output format.

**Comment by DJakov-beep** [comment]
I had the same problem as "musm". What resolved the issue for me, was using an online converter like "Convertio", converting the otf - files to ttf, and then installing the latter. Word embeds the ttf- files without any problems.

**Comment by laurmaedje** [comment]
Our reasons are indeed dubious (bad subsetting and printer issues we had with OTF fonts in the past), so it's not on you to provide TTF support. I was just wondering whether TTF are available because it would allow use to switch to Libertinus earlier rather than waiting until those problems are resolved.

**Comment by alerque** [comment]
Auto-hinted TTFs for this project can be built by removing this line:

https://github.com/alerque/libertinus/blob/master/fontship.mk#L1

Then running `fontship make -- static-ttf`.

You can also download the artifacts from #555 for testing if you like.
