### ISSUE TITLE
Retiring the project

### ISSUE THREAD

**Issue by khaledhosny** [alerque/libertinus#328]
It is been almost 8 years since I started working on this, and it is time to move on since the project is a very low priority to me. I’m be happy to hand out the maintenance to anyone who would be interested.

Please speak out if you are interested in maintaining the project, there is no hard deadline deadline but if no one shows up I might just archive the repository after a month or two.

**Comment by alerque** [comment]
I'd be interested in this.

**Comment by khaledhosny** [comment]
That was quick. Great. How do you want this to happen? I’d rather transfer the repository to a different account/organization and be done with it.

**Comment by alerque** [comment]
Long term I would consider putting this under the umbrella of some open source type foundry such as @theleagueof or @source-foundry. I would want to think through the ramifications of that move and it would likely take some time to negotiate and setup. If you want to get the initial transfer over I'm happy to migrate it to my personal account for the time being. Github is pretty good about leaving a trail of redirects for migrated repositories so it shouldn't be too much disruption even if it results it two moves over the long haul.

I think to do that –since you don't have write access to my user account– you would need to add me with owner privileges to this repository, then I can hit the transfer buttons.

**Comment by capnrefsmmat** [comment]
I'm not in a position to help with maintenance, but I would also like to thank you for your hard work over the years. I have enjoyed using Libertinus and I'm grateful for your effort to make a robust font with OpenType Math support. 

During my PhD I used Libertinus often enough that when I offered my template to a classmate for his dissertation, he changed the font, since Libertinus was "my font"  and would make everyone think I had written it.

**Comment by khaledhosny** [comment]
> you would need to add me with owner privileges to this repository, then I can hit the transfer buttons.

Done.

**Comment by alerque** [comment]
Stand by, I have to get my own personal fork out of the way first!

**Comment by alerque** [comment]
Done.

**Comment by KrasnayaPloshchad** [comment]
Thank you very much!

**Comment by istathar** [comment]
@alerque I'd encourage you to consider moving to @theleagueof. They're a good umbrella crew. I just went through moving another font repo to their organization, as it happens.

**Comment by alerque** [comment]
@istathar I'm would still consider The League of Movable Type as a future home, but not right this minute. I'm more involved there than I was when this was passed off to me, but there are also a lot of restructuring going on and I'm kind of waiting to see how all that shakes down before proposing yet another move for this repository.

Incidentally I've been helping @theleagueof cleanup their Git foo, gathering scattered contributions from forks, and re-releasing fonts. I haven't seen or heard anything about a new repo incoming from you. Which font are you referring to?

**Comment by istathar** [comment]
Oh heh. No, I'm just referring to supporting your suggestion to move sursly's fork back to the main repo.

**Comment by alerque** [comment]
Sorry I misread your message.

**Comment by AdamBlumDev** [comment]
@alerque First of all, I want to thank you for your willingness to take on this project. Like @capnrefsmmat, I've had a long relationship with this typeface (since it was still the Libertine Open Fonts Project) and consider it one of the greatest Open Source contributions ever, certainly the best Open Source typeface.

I do not have much of a presence on the Web, and am certainly not qualified to modify the project; that being said, I have some questions about the future direction of Libertinus. 

Firstly, what do Fontship and The League of Moveable Type bring to the table? Perhaps my lack of personal experience is showing, but I'm curious as to the advantages offered by Fontship in comparison to FontForge, which has a long history. Also, I know LMT was a pioneer of Open Source typefaces on the web, but I feel a bit uncomfortable with their Corporate Sponsorship program. The travesty that is the current W3C has soured my expectations when it comes to these types of programs. I understand the need to financially support type designers, but how will the ones working on the Libertinus project directly benefit from this relationship?

Secondly, who else can weigh in on this conversation? I feel that there are many others who would love to give their feedback, but haven't been made aware of these coming changes. Would it be helpful to seek out opinions of other long-time Libertinus users, so we could get a concensus on future goals?

If I'm overstepping my bounds please let me know, I just care very much about this project and want to see it grow in the future. I trust Caleb's experience and am glad he's being proactive about this.

Best Regards,

Adam

**Comment by alerque** [comment]
@AdamBlumDev First let me clarify a few things, I think you're worried about things being weirder than they are.

First about the build system. This font project was not using FontForge to build the fonts when I got the project. The source files are still in FontForge's format, but there is much better tooling out there for building fonts these days and Khaled had been phasing it out for a long time. It was completely deprecated before I inherited the project. In its place was a custom build script that does some manipulation of font bits before converting the sources to another representation used by *many* open source type related tools these days. From there a standard set of tools were used to generate the necessary parts and assemble them into the final font files. These steps were orchestrated with a custom makefile.

Here's what Fontship brings to the table: The makefile with all of the orchestration and the format conversion are all handled automatically. Tit-for-tat exactly the same thing is being done, the same libraries are use, the same software at every point. The difference is that the process is abstracted so that every font project doesn't have to re-invent the wheel and assemble all the parts. That frees up font projects like this to work on the source of the font without needing as much tooling. It also makes building the font across platforms easier. Note that the custom Python script that manipulates some of the source before passing it on for building is still in place.

The fact that Fontship is under the LOMT repos is neither here nor there. I initially wrote it for use on their font projects, but quickly realized how useful it would be to have a generalized tool that worked to keep non-font code out of font project's way. Someday it might make sense to move it to a different place, perhaps [Source Foundry](https://github.com/source-foundry/) and keep the LOMT repos just for fonts. We'll see.

As for moving this to LOMT namespace, I don't see that happening any time soon. It's an interesting idea, but I have some concerns about their goals and directions too. We'll see how those shake out and whether it's worth the move to try to get some font designer help (something I lack). That's what you should be worried about if anything: I'm a programmer not a designer. I can handle building this font and managing the sources, but actually designing glyphs that match the style to expand the weights? That's the sort of things where you should worry about this projects future!

Before anything like a move to a shared maintainer workspace happens there will be an RFC issue here to make sure I'm not missing anything major that would make this less accessible to people.
