### ISSUE TITLE
Add support for U+1D106 and U+1D107 (musical symbol left|right repeat sign)

### ISSUE THREAD

**Issue by gyuris** [alerque/libertinus#339]
I'm [developing a tool](/gyuris/openlyrics-prototype) for for Christian worship leaders to make chord sheets from XML using CSS. Currently I use previous version of Libertinus (Linux Libertine/Biolinum). I have to format repeating lines with musical repeat signs:
```
𝄆 Repeating line 𝄇
```
Would it be possible to support these two glyphs in Libertinus?

(I'm not a font designer, just a user. I made `Opentype-Features.fodt`)

**Comment by alerque** [comment]
Sure. I once had a use for them myself. However I can give you a heads up that it will be a little while before I can tackle this myself, and even a little (less) while before I could accept such a thing as a contribution if somebody else were to do it. I suggest setting up a character range match in your CSS and fallback to another font that supports this for those glyphs. It's a bit of a hack but I don't want to hold your project up.

Also if you know of another font that has these glyphs under a compatible license we could steal them from that would be a great foot forward.

**Comment by gyuris** [comment]
Thanks Caleb for responding!

Another fonts that support these glyphs:
- [Vollkorn](https://github.com/FAlthausen/Vollkorn-Typeface/) (SIL Open Font License)
- [FreeSerif](http://savannah.gnu.org/projects/freefont/) (GNU GPLv3)

**Comment by gitjeff2** [comment]
@gyuris I know you said you're using CSS, but have you considered handling this with [LilyPond](http://lilypond.org/)? I've never used it, but there is a MusicXML plugin that might meet your needs.

**Comment by alerque** [comment]
I've used LilyPond extensively too and love it¹, but it's more for sheet music than chords. Of course you can add cords to sheet music, but it's not great at just typesetting lyrics with chords. Personally I consider than lazy-music anyway, but my opinion doesn't count for much. I'm the guy that can't carry a tune in a dumptruck.

If CSS matching CSS to screen slides wasn't a requirement I'd say use SILE (maybe with the *chordmode* package, maybe just custom tags for handling MusicXML) for PDF output.;-)

<sub>¹ Also hate it because of the scheme-based syntax, but it's text based and hence versionable and gives great results, so that's a win overall.</sub>

**Comment by gyuris** [comment]
Thanks @gitjeff2 and @alerque for your suggestions. 

I use [OpenLyrics](https://openlyrics.org) with [OpenLP](https://openlp.org/) for projecting songs and my goal is to provide chord sheets from OpenLyrics XML source files. I know about MusicXML and Lilypond but I think this is another task. I'm mostly done ([sample](https://github.com/gyuris/openlyrics-prototype/blob/master/export-pdf/How%20Great%20Is%20Our%20God%20(Chris%20Tomlin%2C%20Ed%20Cash%2C%20Jesse%20Reeves).xsl.pdf)). There are only such small details left as for example the correct display of repetitive signs. But I can live without them :smiley:.
