### ISSUE TITLE
What happened to sfdnormalize.py?

### ISSUE THREAD

**Issue by ctrlcctrlv** [alerque/libertinus#360]

**Comment by alerque** [comment]
I extracted the source code (& history) from this repository and promoted it to [its own project](https://github.com/alerque/sfdnormalize). In the process I also dug up the history of where it came from before it lived here (Dejavu Fonts & FontForge repos & mailing list) and included that back history.

Once it had a life as its own project (including being [published to PyPi](https://pypi.org/project/sfdnormalize/)) I integrated it into [Fontship](https://github.com/theleagueof/fontship)'s default workflow so that it is automatically part of the build process. All fonts are built using normalized sources, but you can also choose to normalize the sources (e.g. for the purpose of commiting them) by running `fontship normalize`.

**Comment by ctrlcctrlv** [comment]
Thanks for the detailed history. Sorry for bothering you.
