### ISSUE TITLE
l p kerning incorrect in italics?

### ISSUE THREAD

**Issue by istathar** [alerque/libertinus#361]
Noticed that there's some weird kerning going on with the word "alpha" when Libertinus Math is used as compared to italics.

```tex
\textit{alpha} $alpha$
```
![image](https://user-images.githubusercontent.com/1088511/93425946-62ba9c80-f8fe-11ea-83ae-f5c39699d10d.png)

the space between the `l` and the `p` is unexpected.

**Comment by khaledhosny** [comment]
Kerning is not applied in math mode by most OpenType math engines.

**Comment by alerque** [comment]
Even wit kerning out of the picture it looks like the left/right side bearings might be out of whack. Why else would `al` be tighter but `lp` be looser? Perhaps kerning is compensating for this up in regular mode, but in math mode the side bearings by themselves should have done a better job, no?

**Comment by khaledhosny** [comment]
The `l` has italic correction applied to it so it does not bump into super scripts or non-italic symbols after it (e.g. `l^2`, `|l|`, `(l)`).

**Comment by khaledhosny** [comment]
Probably italic correction shouldn’t be applied here (I can’t check the font right now to see if it is really italic correction or math `l` side bearings).

**Comment by khaledhosny** [comment]
Oh, or may be it is the `p` not the `l`, in non-math italic the `p` would have a -ve left side bearing, but we can’t do this in math because of `(p` or `|p`, and there is no equivalent for italic correction for the left side of the glyph.

**Comment by ivo-s** [comment]
We bumped into bearings of mathematical glyphs in #252. As Khaled explained at the time, math mode in standard Xe/LaTeX always applies italic correction, but no kerning. If those glyphs are only used in math mode (which they should be), italic correction essentially determines the effective right-side bearings. These bearings were revised and should be more or less correct. The reason for the wide bearings of `l` and `p` is the combination with characters like parentheses. Other glyphs look similarly uneven, when combined.

![image](https://user-images.githubusercontent.com/7095181/103247210-67173c80-4966-11eb-824f-8693eddcd330.png)

So the answer to this issue would be that it is not a font bug. The bearings have to be like they are, because standard TeX does not do any kerning in math mode. This is partially understandable, because math mode is not intended for writing words. For typesetting descriptive words in math mode, I recommend using `\text{}` supplied by `amsmath`, or `\mathrm{}`/`\mathit{}`.

**Comment by alerque** [comment]
Thanks for all the input here guys. As far as I understand it this issue is not actionable for the reasons given already. If I'm missing something feel free to pipe up, but I'm closing it for now.
