### ISSUE TITLE
Diacritical mark placement under in the italic "ṃ"

### ISSUE THREAD

**Issue by fontu** [alerque/libertinus#384]
(1) Put the diacritical mark in the italic "ṃ" on the extended middle line like the Spectral.
(2) The italic "sārathi" in roman parentheses is too right, compared with the other two fonts.
![m](https://user-images.githubusercontent.com/72780791/95819599-5b51ac00-0d61-11eb-9f74-917b7fbb5c36.PNG)

**Comment by alerque** [comment]
In the future please open separate issues for unrelated requests.

1. I can re-align that diacritical mark no problem.

2. I'm not sure this is 'fixable'. There really isn't any difference in the other fonts you show either except their parenthesis are a bit taller so the dodge the bullet a touch. The issue here is that you are switching from Italic to Roman and your typesetting software (whatever this is) isn't adding any kern compensation. The font itself doesn't have a way to describe kerning situations between different fonts (which is what this situation works out to be). The only this it does is provide a generic italic compensation value that software can use to add a kern at the end of Italic runs to transition to Roman. Some software uses this, others does not. For example compare these two outputs, the first is from XeLaTeX and `\usepackage{libertinus-otf}`, the second is from LibreOffice Write. In both cases the first line is Roman parenthesis and Italic text, the second line is all Italic. You can see the subtle difference in the Italic→Roman transition in XeLaTeX which applied Italic correction automatically.

    ![image](https://user-images.githubusercontent.com/173595/95825425-7f00fc00-0d39-11eb-9606-2b1db922b8f2.png)

    As you can see one way to work around this is to use Italic parenthesis whenever you have *only* Italic text in them.

**Comment by fontu** [comment]
Thank you. Here are additional suggestions:

(1) Can the apostrophe font be narrower like the Junicode?
(2) The em-dash font seems too short. Can it be longer?
(3) The number "1" looks lower than "2" below. Can they look the same in height?
![2](https://user-images.githubusercontent.com/72780791/95836608-9c09ef00-0d7a-11eb-9691-762017ed7896.PNG)
?

**Comment by alerque** [comment]
@fontu I said please open one issue per topic please. I am not going to track a running list of running requests appended to unrelated issues. See #323 for the apostrophe issue we are already dealing with. If you want the others to be considered please open separate issues to track the decision and status.

**Comment by kimmus** [comment]
With regard to the mix of regular brackets and italic text: a traditional rule of typography, still observed in mathematical formulae, calls for brackets of all kinds—( ) [ ] { } etc.—never to be italicised. See e.g. Bringhurst: _The Elements of Typographic Style_ (1992 etc.). The ‘G’ (Graphite) versions of Linux Libertine have a feature for this.

**Comment by alerque** [comment]
@kimmus If you know of anything in OpenType we aren't implementing as well as we could be that would help more applications compensate for italic→roman transitions I'd be happy to consider it. But it's unrelated to the original issue here, so please open a new issue if you think there is something to do.
