### ISSUE TITLE
Missing glyph

### ISSUE THREAD

**Issue by Pierre3888** [alerque/libertinus#407]
Hi,
I'm leaving Linux Libertine G to Libertinus serif

AFAIK Glyph E15D of Linux Libertine G is missing in Libertinus like others glyph in this aera
Is it a bug ? will it be solved ?

![buglibertinus](https://user-images.githubusercontent.com/74811768/99870691-7f60a280-2bd5-11eb-8f4d-236794dc9a5f.png)
Pierre

**Comment by hvoss49** [comment]
They are in LibertinusSerif-Regular.otf, see 0x1100be

**Comment by Pierre3888** [comment]
Thanks for this quick answer. I got it now
I search for it in Libertinus sans; and didn't got it ?
Same problem (me) ? or missing glyph

**Comment by alerque** [comment]
@Pierre3888 The *Libertinus Serif* font family is a direct decedent of *Linux Libertine* and should have 100% of the same coverage (and quite a bit more added since). The *Libertinus Sans* family is descended from *Linux Biolinum* and again has more coverage than the original. That being said the Sans family has considerable less character coverage than the Serif family (as was the case for Biolinum compared to Libertine). If there are specific character(s) needed in the Sans family I'm happy to consider adding them (and of course will accept contributions if anybody does the work!).

I can keep this issue open to track ad addition request to the Sans family, just as long as it's clear this isn't a regression over the Libertine family.

**Comment by Pierre3888** [comment]
@alerque 
It seems that Latin subscript small letters b, c, d, f, g, h, i, j, m, n, p, q, r, s, t, u, v, w, y are missing in libertinus sans but present in Linux Biolinium G
