### ISSUE TITLE
Enabling CASE disables ONUM

### ISSUE THREAD

**Issue by Amphiboly** [alerque/libertinus#408]
As stated, Tested with LibertinusSerif-Regular.otf 7.020 Release using ConTeXt and Libre Office 7.
[Case_and_Onum.pdf](https://github.com/alerque/libertinus/files/5585879/Case_and_Onum.pdf)

**Comment by alerque** [comment]
Thanks for the report. I'd be happy to fix this if it was actually an error, but I think (pardon the pun) in this case it's actually the expected behavior.

According to [Microsoft's OpenType spec](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-case) (if spec is the right word for a rambling non-definitive hodge-podge of pseudo documentation) this is the correct behavior, CASE is supposed to also enable LNUM (which is the opposite of ONUM) so disabling ONUM makes sense (emphasis added):

> Function: Shifts various punctuation marks up to a position that works better with all-capital sequences or sets of lining figures; **also changes oldstyle figures to lining figures**.
