### ISSUE TITLE
Bad automatic sizing for "⟨" and "⟩" using xelatex and lualatex

### ISSUE THREAD

**Issue by kauesena** [alerque/libertinus#412]
**Describe the bug**
Automatic sizing of \langle and \rangle with XeLaTeX and LuaLaTeX does not work properly. 
**Steps to reproduce**
```tex
\documentclass{article}
\RequirePackage{unicode-math}
      \setmainfont{Libertinus Serif}
      \setmathfont{Libertinus Math}
\begin{document}
	\[
	\left\langle \sum_{j} A\middle\vert B\right\rangle \quad \left\langle \sum_{j} A\middle\vert B\right\} \quad \left\{ \sum_{j} A\middle\vert B\right\}
	\]
\end{document}
```

**Expected vs. actual behavior**
Delimiters to have the same size. 

**Screenshots / logs**
![image](https://user-images.githubusercontent.com/30255100/103108111-6d827d00-4623-11eb-832a-02d211421813.png)

**Comment by kauesena** [comment]
#242

**Comment by alerque** [comment]
Hey @ivo-s do you happen to have any idea what the actual trouble is here? I'm completely out of my depth on math related typesetting. A quick scan of the SFD sources suggests that the brace glyphs have sizes ranging from default up to `.size12` while parens and angle braces only have up through `.size4`. Is that the limiting factor here? I'd be happy to accept a fix if anybody knows how this should be handled.

**Comment by khaledhosny** [comment]
You need more size glyphs, in the past I often took a shortcut and just copied them from STIX Two Math, which might be the solution here if the style is not to different from the existing one and STIX Two Math has the extra glyphs.

**Comment by ivo-s** [comment]
Khaled is correct, the maximum size for angle brackets is size4. For reference, the relevant section is vert. variants in the MATH table (Element -> Other info -> MATH info). Previously, the issue was an incomplete entry in the table, but here the bigger glyphs are just missing.

STIX2 has a similar style, but not exactly the same angle and thickness. I think the best solution is to just draw the new glyphs. The shape is simple, but one needs to make the proper scaling of height, width, and stroke thickness so it looks nice. If someone would like to fix it, please write it here. Otherwise, I'll look into it next week.

While we're discussing angle brackets – I noticed that the vertical placement is different than other brackets. Also the angle brackets do not have the same visual thickness as the vertical bracket, which is a very common pairing (bra-ket) in quantum physics.

![ket](https://user-images.githubusercontent.com/7095181/103157664-aeaa9680-47b5-11eb-9840-385ba534df14.png)

Considering other brackets, it would probably be best if `|` got a bit thicker. How open are you to changes in this regard?

**Comment by khaledhosny** [comment]
I’m positive that I didn’t draw any of these glyphs and copied them from some version of STIX that probably had a limited number of sizes, so it would make sense to replace the current one with the updated STIX Two version.
