### ISSUE TITLE
LO Writer 7 Win: tt changed to 5 (+ other ligatures problems)

### ISSUE THREAD

**Issue by crti** [alerque/libertinus#420]
On Windows 10 x64 I installed the Libertinus-7.020.zip release fonts. 
Then in LibreOffice 7.0.4.2 x64 Writer I used a ODT template with Libertinus Serif as Standard text font. 
When I write a word with two t those are changed to 5 with seemingly some space behind. 
![tt-Libertinus-LOW-issue](https://user-images.githubusercontent.com/1004113/103759529-29747c80-5014-11eb-8415-2018b00d6ec1.png)

I then downgraded to Libertinus-6.12 release fonts. Then 8 instead of 5 seems to be shown. Also other ligatures seem to not work in this setup. Unsure if LibreOffice Writer or the Libertinus font releases are causing this? 

![tt-Libertinus-LOW-issue](https://user-images.githubusercontent.com/1004113/103760534-86246700-5015-11eb-80d0-224d5680dbdb.png)

Sorry if this is an obvious behavior (already known). I did not invest time in typography in LibreOffice Writer in the last years.

**Comment by crti** [comment]
I did further testing by reinstalling Libertinus-7.020 and comparing to Linux Libertine G where the ligatures in Writer seem to be displayed fine: 
![tt-Libertinus-LOW-issue-7 020](https://user-images.githubusercontent.com/1004113/103762282-588ced00-5018-11eb-9660-2a206ea1cf10.png)

I then exported a PDF from Writer and there the Ligatures also for the 7.020 text seem correct. 
![tt-Libertinus-LOW-issue-7 020-PDF](https://user-images.githubusercontent.com/1004113/103762337-6f334400-5018-11eb-84a4-7db629a1dd2f.png)

So this seems like an odd/buggy LibreOffice Writer display issue. Will see if I find any bug reports about this.

**Comment by crti** [comment]
I just installed LibreOffice 6.4.6 Portable and there everything seems fine. So the issue here can be closed.
![tt-Libertinus-LOW-6 x-7 020](https://user-images.githubusercontent.com/1004113/103767764-7f9bec80-5021-11eb-9277-03d4321754a5.png)

**Comment by alerque** [comment]
This kind of glitchy display is caused by your system having more than one copy of the font installed. On Windows this can happen even when the font was used and still in memory then updated on disk. One way or another what is happening is you are looking up glyph ids in one venison of the font files but rendering them from a different one. The glyph ids of generated fonts tends to change whenever a character is added or removed from a font (even when the source ids don't shuffle).

The solution is *always* to make certain sure you only have one copy of the relevant font(s) installed anywhere your system sees fonts. Note systems that have both system and user font installation locations are particularly susceptible to this. Then when you are sure there is only one, reboot (especially on Windows) to clear system and app memory caches.
