### ISSUE TITLE
Adding support for web font icons instead of text description.

### ISSUE THREAD

**Issue by lkhphuc** [alerque/libertinus#427]
**Describe the bug**
Adding support for more web font icons.

**Steps to reproduce**
I love this font so much that I override font on all website with Libertinus, by disabling "Allow pages to choose their own font" Firefox browser setting. However in some sites, the "icons" are replaced with text and some time make the site unusable or unpleasant to use. 
![Screenshot 2021-01-14 at 11 57 19](https://user-images.githubusercontent.com/12573521/104587974-a9779380-565f-11eb-9115-cdb4f2c5d1d2.png)

**Expected vs. actual behavior**
![Screenshot 2021-01-14 at 12 00 51](https://user-images.githubusercontent.com/12573521/104588360-27d43580-5660-11eb-8a3c-c3c2516d2465.png)

**Comment by alerque** [comment]
I'm glad you like the fonts, but I think this suggestion is out of scope for the project. My suggestion is to find a less aggressive way of changing fonts that doesn't catch places where text styling is used in lieu of content.

Maintaining a compatible set of emoji, logo, and iconography symbols is a huge undertaking and I think there are much better ways to spend developer time on this font that would fit its goals better. There are several projects that develop large sets of iconography. Adding one or more of these to your font fallback stack might alleviate the issue somewhat.

Additionally since not all systems that use fonts for icons use the same ways of encoding them: some use PUA glyphs, others use ligatures, others use other tricks. Websites are designed with a specific system of encoding them and matching font in mind. There is no good way to make a general purpose replacement.

Either of these would be show stoppers on their own, it's simply too big a project for no gain over other existing projects and even if I had all the time in the world I don't think there even *is* a technical way to do it that would be a suitable global replacement for all the ways people hack together icon fonts.

Lastly, I personally don't even think fonts should be used for this sort of thing, I think SVG icon systems are at the point where they are more appropriate for use that hacking fonts. I wouldn't want to perpetuate a system I think is technologically inferior to other current options.

**Comment by lkhphuc** [comment]
Thank for your comment. That is totally reasonable.
I kinda suspect the same reasoning but since I has no expertise and failed to find any other fix so just want to raise this issue here.
