### ISSUE TITLE
Integral glyphs should provide kerning info, not rely on engines’ non-standard corrections

### ISSUE THREAD

**Issue by OlivierNicole** [alerque/libertinus#447]
It looks like integral glyphs in Libertinus Math don’t have kerning information. As a consequence, when you attempt to typeset it using an engine that strictly adheres to the OpenType standard (like [experimental math support in SILE](https://github.com/sile-typesetter/sile/pull/1103/) tries to do), the limits are far from the integral sign and it looks bad.

![image](https://user-images.githubusercontent.com/14031333/109415768-eeab1700-79ba-11eb-9b71-0cbf54b157ec.png)
(here with a slanted integral (`+ss08` feature) to make the problem even more visible.)

The reason why integrals look nice in other engines is that they do ad hoc, non-standard corrections. This is documented in LuaTeX’s manual: for “big operators” in `nolimits` mode, the superscript is not shifted, while the subscript is shifted left by the amount of the italic correction. (This is the default mode. A LuaTeX parameter provides other modes with different ad hoc corrections.)

![image](https://user-images.githubusercontent.com/14031333/109416159-cc19fd80-79bc-11eb-8fe4-46c596beb5c3.png)

This contrasts with the standard typesetting of sub-superscripts, where the superscript is shifted to the right by the amount of the italic correction, and the subscript is not shifted.

The reason these corrections were implemented is that many OpenType math fonts lack kerning information for these glyphs. Of course, it is an easy fix to implement, but it seems to me that it would be better to move toward adding such information, rather than keep relying on a poorly documented convention. (I couldn’t find it documented in XeTeX for example.)

**Comment by ivo-s** [comment]
Hello Olivier and thanks for bringing this up. These slanted integrals were added by me in #419, and I thought that italics correction was the correct way of handling that.
https://docs.microsoft.com/en-us/typography/opentype/spec/math
As it turns out, the fact that italics correction _can_ be used for this, does not mean it _should_.

If I understand correctly, you are referring to the MathKernInfo table. I completely missed that earlier. It provides kerning values for each height separately, so that the sub/superscripts can be positioned even for the wiggliest of glyphs.

This introduces more complexity into how exactly we should set the side bearings, italics correction, and the kerning values. However, I am a bit confused, because it does not seem to add up.
First consideration: the limits (positioned directly above and below the base glyph) are shifted by 1/2 italics correction to the left and right. This means that the base glyph needs to have symmetrical side bearings and also the italics correction needs to follow approximately how slanted the glyph is (as it is now).
Second consideration: the subscript should be put right after the right bearing of the base glyph, while the superscript is shifted by italics correction. This means that the base glyph should _not_ have symmetrical bearings, but rather set the bearings relative to the bottom, and the slanted top should follow the italics correction.

Both considerations follow from the OpenType standard linked above, but they seem to be in conflict. In theory, one could fix the sub/superscripts with kerning, but that would basically use math kerning mainly to cover one big offset (your top picture). XeTeX solves this by shifting the subscript instead of the superscript, as you mentioned. I agree the ideal solution would be to conform to the OpenType standard and also make the font work in Xe/LuaTeX. I can try some experimenting, but it would be very helpful if you could advise me on this.

**Comment by khaledhosny** [comment]
The special handling of italic correction is part of the the OpenType math layout and not an engine-specific hack, MS implantation does it and both XeTeX and LuaTeX follow it (though LuaTeX like to add its own extensions complicating things). The OpenType “standard” is under-specified, and math layout is no exception. MathKern is an additional, more powerful mechanism,  and fonts are not required to have it.

**Comment by OlivierNicole** [comment]
@ivo-s I did not mean to say that this happens only with your slanted integrals; the default ones are also affected, because they have a slight slant.

@khaledhosny I see, this is useful to know. If OpenType math is under-specified, is experience the only way to learn peculiarities like this one?

**Comment by khaledhosny** [comment]
> If OpenType math is under-specified, is experience the only way to learn peculiarities like this one?

Pretty much. I asked the responsible MS developer to clarify this almost 10 years ago, even before MATH table spec was made public, but nothing happened. You might have better luck asking on https://github.com/MicrosoftDocs/typography-issues/issues these days (using the feedback link at the end of https://docs.microsoft.com/en-us/typography/opentype/spec/math, which will use the proper issue template).

**Comment by OlivierNicole** [comment]
Thank you, will do.

I guess this is a non-issue, then.
